### PR TITLE
Add Samsung Tab commits to main tree

### PR DESCRIPTION
**Pull request by 488315**

### CODE REVIEW

**Review by josip-k — COMMENTED** [review]
@488315 Why are we importing livedisplay and touch HALs to the device tree? Is there any changes that only reflect on the tablet? If so, i suggest moving them to the device-specific tree instead.

**Comment by 488315** [comment]
Livedisplay and Touch has worked for @guckesh too, he tested on his build so it would work for the common tree.
image
image

**Comment by 488315** [comment]
> @488315 Why are we importing livedisplay and touch HALs to the device tree? Is there any changes that only reflect on the tablet? If so, i suggest moving them to the device-specific tree instead.

I would need to merge the Sepolicy fixes into one commit so its easier and i need to refactor it for lineage hals

**Comment by josip-k** [comment]
> Livedisplay and Touch has worked for @guckesh too, he tested on his build so it would work for the common tree. image image

Couldn't we use touch HAL from hardware/samsung?

**Comment by 488315** [comment]
> > Livedisplay and Touch has worked for @guckesh too, he tested on his build so it would work for the common tree. image image
> 
> Couldn't we use touch HAL from hardware/samsung?

The Hardware/Samsung Touch Hal has 
https://github.com/LineageOS/android_hardware_samsung/blob/lineage-21/hidl/touch/StylusMode.cpp
which the device doesnt have `hover_mode` in their features 

`    ~  adb shell cat /sys/class/sec/tsp/cmd_list                                                                                                                                                                                          ✔  at 02:25:11 AM  
++factory command list++
fw_update
get_fw_ver_bin
get_fw_ver_ic
get_config_ver
get_threshold
module_off_master
module_on_master
module_off_slave
module_on_slave
get_chip_vendor
get_chip_name
run_jitter_test
run_factory_miscalibration
run_factory_miscalibration_read_all
run_miscalibration
get_wet_mode
get_module_vendor
get_x_num
get_y_num
get_checksum_data
get_crc_check
run_reference_read
get_reference
run_rawcap_read
run_rawcap_read_all
get_rawcap
run_delta_read
get_delta
run_cs_raw_read_all
run_cs_delta_read_all
get_pat_information
set_external_factory
tclm_test_cmd
get_calibration
run_ix_data_read
run_ix_data_read_all
run_self_raw_read
run_self_raw_read_all
run_trx_short_test
check_connection
get_cx_data
run_vpump_cap_data_read
run_cx_data_read
run_cx_data_read_all
get_cx_all_data
run_cx_gap_data_x_all
run_cx_gap_data_y_all
get_strength_all_data
run_high_frequency_rawcap_read_all
run_snr_non_touched
run_snr_touched
set_tsp_test_result
get_tsp_test_result
increase_disassemble_count
get_disassemble_count
glove_mode
clear_cover_mode
report_rate
set_wirelesscharger_mode
set_grip_data
dead_zone_enable
spay_enable
aot_enable
aod_enable
set_aod_rect
get_aod_rect
fod_lp_mode
fod_enable
set_fod_rect
singletap_enable
external_noise_mode
set_touchable_area
delay
debug
factory_cmd_result_all
run_force_calibration
set_factory_level
fix_active_mode
touch_aging_mode
run_sram_test
set_sip_mode
set_note_mode
set_game_mode

`

**Comment by 488315** [comment]
https://github.com/dmXq-development/android_device_samsung_sm8550-common/commit/b90e95679cddf800a8c8817e861d33a67a1d4e80  This Commit would be moved the common tree as well.

**Comment by 488315** [comment]
Reopening issue

**Comment by 488315** [comment]
.

**Pull request closed without merging**
